//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyDescription("This project describes how to pre cache all files for an XAF application")]
[assembly: AssemblyCompany("Fa. Manuel Grundner")]
[assembly: AssemblyProduct("how-to-precache-an-xaf-winforms-application.Win")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0.0+4861b561fe75ad358e7cf46f200e803a78024ac0+topic/rename-app")]
[assembly: AssemblyCopyright("Copyright Manuel Grundner © 2019")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("")]

